# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uenmZAi8JFdfcDJxsfQa8l3-1FHdCRD
"""

import pickle

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.pipeline import Pipeline

# collect data
df = pd.read_csv(r"C:\Users\krish\Downloads\Project-1-cdgi\Datasets\Housing.csv")

# find missing data
print(df.isnull().sum())

df['price'] = df['price'].fillna(df['price'].mean())
df['bedrooms'] = df['bedrooms'].fillna(df['bedrooms'].mode()[0])
df['bathrooms']  = df['bathrooms'].fillna(df['bathrooms'].mode()[0])
df['stories'] = df['stories'].fillna(df['stories'].mode()[0])

le = LabelEncoder()
cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']
for c in cols:
    df[f'{c}'] = le.fit_transform(df[f'{c}'])

x = df.drop("price",axis=1)
y = df['price']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)


pipeline = Pipeline(
    [
        ("scaler",StandardScaler()),
        ('model',LinearRegression())
    ]
)

pipeline.fit(x_train,y_train)


# save model 
pickle.dump(pipeline,open("model.pkl","wb"))
